import { PROGRAM_TYPES } from "router/menus";

export const mock_userAccessibleMenus: PROGRAM_TYPES[] = [
  PROGRAM_TYPES.SAMPLE_REGISTRATION,
  PROGRAM_TYPES.SAMPLE_LIST,
  PROGRAM_TYPES.SAMPLE_LIST_AND_MODAL,
  PROGRAM_TYPES.SAMPLE_LIST_AND_DRAWER,
  PROGRAM_TYPES.SAMPLE_LIST_WITH_LIST,
  PROGRAM_TYPES.SAMPLE_LIST_WITH_FORM,

  PROGRAM_TYPES.DASHBOARD,
  PROGRAM_TYPES.SETTING,
];
